name: 运行主程序
on:
  workflow_dispatch:
  push:
    paths:
      - "reinstall.sh"
      - "trans.sh"
      - ".github/workflows/run_reinstall.yml"
jobs:
  run:
    name: 运行主程序
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: dd
        run: sudo bash reinstall.sh --debug --password 123@@@ dd --img=https://download.opensuse.org/tumbleweed/appliances/openSUSE-MicroOS.x86_64-SelfInstall.raw.xz
      - name: alpine
        run: sudo bash reinstall.sh --debug --password 123@@@ alpine
      - name: debian
        # debian/ubuntu are forced to cloud_image mode in reinstall.sh,
        # passing --ci is redundant
        run: sudo bash reinstall.sh --debug --password 123@@@ debian
      - name: ubuntu
        run: sudo bash reinstall.sh --debug --password 123@@@ ubuntu
