name: 运行主程序
on:
  workflow_dispatch:
  push:
    paths:
      - "reinstall.sh"
      - "trans.sh"
      - ".github/workflows/run_reinstall.yml"
jobs:
  run:
    name: 运行主程序
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: dd
        run: sudo bash reinstall.sh --debug --password 123@@@ dd --img=https://download.opensuse.org/tumbleweed/appliances/openSUSE-MicroOS.x86_64-SelfInstall.raw.xz
      - name: alpine
        run: sudo bash reinstall.sh --debug --password 123@@@ alpine
      - name: debian cloud image
        run: sudo bash reinstall.sh --debug --password 123@@@ debian --ci
      - name: ubuntu cloud image
        run: sudo bash reinstall.sh --debug --password 123@@@ ubuntu --ci
